config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :post

  after_create :increment_post_comments_counter

  alias_attribute :author, :user

  def increment_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_create :increment_post_likes_counter

  def increment_post_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_create :increment_user_posts_counter
  before_validation :initialize_counters, on: :create

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def increment_user_posts_counter
    author.increment!(:posts_counter) if author.present?
  end

  private

  def initialize_counters
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_initialize :set_default_posts_counter

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def set_default_posts_counter
    self.posts_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Devise::Controllers::Helpers

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation bio photo])
  end
end

app/controllers/comments_controller.rb
# app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user, only: %i[new create]

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params.merge(user: @user))

    if @comment.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_user
    @user = current_user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(user: current_user)

    if @like.save
      redirect_to user_post_path(@post.author, @post), notice: 'Like added successfully.'
    else
      redirect_to user_post_path(@post.author, @post), alert: 'Error adding like.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_user, only: %i[new create]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:author, :comments).page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user)
  end

  def new
    @post = @user.posts.new
  end

  def create
    @post = @user.posts.new(post_params)

    if @post.save
      flash[:success] = 'Post was successfully created.'
      redirect_to user_posts_path(@user)
    else
      flash.now[:error] = 'Failed to create the post.'
      render :new
    end
  end

  private

  def set_user
    @user = current_user
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
# user_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    if params[:id] == 'sign_out'
      sign_out current_user
      redirect_to new_user_session_path, notice: 'Successfully signed out. Please log in.'
    else
      @user = User.find_by(id: params[:id])

      if @user
        @recent_posts = @user.recent_posts
        @all_posts = @user.posts
      else

        redirect_to root_path, alert: 'User not found.'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= form_with(model: [@user, @post, Comment.new], url: user_post_comments_path(@user, @post), method: :post) do |form| %>
  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit "Create Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'users', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'registration', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{name}" %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post">
    <div class="post-header">
      <div class="user-details">
        <% if post.author.photo.present? %>
          <%= image_tag post.author.photo, alt: "User Photo" %>
        <% else %>
          <p>Photo not available</p>
        <% end %>
        <p><%= post.author.name %></p>
      </div>
    </div>

    <div class="post-details">
      <%= link_to user_post_path(post.author, post) do %>
        <h2><%= post.title %></h2>
        <p><%= post.text %></p>
        <p>Number of Likes: <%= post.likes_counter %></p>
        <p>Number of Comments: <%= post.comments_counter %></p>
      <% end %>

      <%= button_to "Like", user_post_likes_path(@user, post), method: :post, remote: true %>
    </div>

    <div class="comments-section">
      <h3>Comments</h3>
      <% post.recent_comments.each do |comment| %>
        <p><strong><%= comment.user.name %>:</strong> <%= comment.text %></p>
      <% end %>

      <%= link_to "Create New Comment", new_user_post_comment_path(@user, post) %>
    </div>
  </div>
<% end %>
<div class="pagination">
<%= paginate @posts %>
</div>


<%= link_to "Back to Users", users_path %>
<%= link_to "Create New Post", new_user_post_path(@user) %>

app/views/posts/new.html.erb
<%= form_for @post, url: user_posts_path(@user), method: :post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<!-- app/views/posts/show.html.erb -->

<h1><%= @post.title %></h1>

<div class="post-details">
  <p><strong>Post by:</strong> <%= @post.author.name %></p>
  <p><strong>Comments:</strong> <%= @post.comments_counter %></p>
  <p><strong>Likes:</strong> <%= @post.likes_counter %></p>
</div>

<div class="post-content">
  <h2>Post Content</h2>
  <p><%= @post.text %></p>
</div>

<div class="comments-section">
  <h3>All Comments</h3>
  <% @comments.each do |comment| %>
    <div class="comment">
      <p><strong>Username:</strong> <%= comment.user.name %></p>
      <p><%= comment.text %></p>
    </div>
  <% end %>
</div>

<%= link_to "Back to Posts", user_posts_path(@post.author) %>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->


<div class="top">
<h1>All Users</h1>
<div>
<% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% end %>
</div>
</div>

<div class="user-list">
  <% @users.each do |user| %>
    <div class="user-card">
      <%= link_to user_path(user) do %>
        <div class="user-picture">
          <% if user.photo.present? %>
            <%= image_tag user.photo, alt: "User Photo" %>
          <% else %>
            <div class="placeholder">No Photo Available</div>
          <% end %>
        </div>
        <div class="user-info">
          <div class="username-box">
            <p><%= user.name %></p>
          </div>
          <div class="post-count">
            <%= pluralize(user.posts.count, "post") %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->


<div class="top">
<h1><%= @user.name %></h1>
<div>
<% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  <% end %>
</div>
</div>

<div class="user-profile">
  <div class="user-details">
    <% if @user.photo.present? %>
      <%= image_tag @user.photo, alt: "User Photo" %>
    <% else %>
      <p>No Photo Available</p>
    <% end %>
    <p>Number of Posts: <%= @user.posts_counter %></p>
  </div>

  <div class="user-bio">
    <p><%= @user.bio %></p>
  </div>
</div>

<div class="user-posts">
  <% if @recent_posts.empty? %>
    <p>No recent posts available.</p>

    <%= link_to "Create New Post", new_user_post_path(@user) %>
  <% else %>
    <% @recent_posts.each do |post| %>
      <div class="post">
        <h2><%= post.title %></h2>
        <p><%= post.text.truncate(200, separator: ' ') %></p>
        <p>Number of Comments: <%= post.comments_counter %></p>
        <p>Number of Likes: <%= post.likes_counter %></p>
      </div>
    <% end %>

    <% if @recent_posts.size < 4 %>
      <%= link_to "Create New Post", new_user_post_path(@user) %>
    <% end %>

    <%= link_to "See All Posts", user_posts_path(@user) %>
  <% end %>
</div>